#!/usr/bin/env bash
# vim: noai:ts=4:sw=4:expandtab
# shellcheck source=/dev/null
#
# Syskit: A system health monitor built in bash version 5.3+
# https://github.com/4kit1-glitch/syskit
#
#

# shellcheck disable=2034,2155
readonly VERSION=0.0.1
readonly PROGNAME=$(basename "$0")

#sys_locale=${LANG:-C}

# Speed up script by not using unicode.
LC_ALL=C
LANG=C

# at the moment config files will be stored in shm folder for testing purposes

# shellcheck disable=2155
export SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${SCRIPT_DIR}/.config}
export DUMPS_PATH=${DUMPS_PATH:-${SCRIPT_DIR}/logs}
export CACHE_PATH=${CACHE_PATH:-${SCRIPT_DIR}/.cache}
export CONFIG_DIR="$CACHE_PATH/sysk"
export ENGINE_DIR=${ENGINE_DIR:-${SCRIPT_DIR}/engine}
export RULE_DIR="$ENGINE_DIR/.rules"
export RESULT_DIR="$ENGINE_DIR/results"
export DATE="$(date +%Y_%m_%d)"

PATH=$PATH:/usr/xpg4/bin:/usr/sbin:/sbin:/usr/etc:/usr/libexec

set -euo pipefail

export CORE_DIR="$SCRIPT_DIR/lib/core"
export DEVICE_DIR="$SCRIPT_DIR/lib/devices"
export HW_DIR="$SCRIPT_DIR/lib/hw"
export FEATURE_DIR="$SCRIPT_DIR/features"


# ----------------------- source scripts ---------------------

# source core scripts
for script in "$CORE_DIR"/*.sh; do
    source "$script"
done

# source device scripts
for dir in "$DEVICE_DIR"/*; do 
    for script in "$dir"/*.sh; do
        source "$script"
    done
done

# source hw scripts
for script in "$HW_DIR"/*.sh; do 
    source "$script"
done

main() {
    # check req files
    # check req dirs
    # install mising deps
    # comfirm installation
    # run data collections
    # run inference engine and generate results
    # run decision engine and generate results
    # run tui if -q flag isnt given which just pretty print results and decition
    # exit 
    check_req_files || {
        printf "Required files missing" >&2
        exit "$ERR_FAILURE"
    }
    check_req_dirs || {
        printf "Required directories missing" >&2
        exit "$ERR_FAILURE"
    }

    parse_args "$@"
    # installing missing dependencies
    install_missing_deps

    # running data collections
    write_cpu_json &
    write_memory_json
    write_thermal_json
    write_disk_json 
    write_sound_json
    
    # create dumps path
    mkdir -p "$DUMPS_PATH"
    
    # run engine
    python3 "$ENGINE_DIR"/inference.py && python3 "$ENGINE_DIR"/decision.py

    display_tui || {
        exit "$ERR_FAILURE"
    }
    exit "$ERR_SUCCESS"
}

main "$@"
